name: Build and Release Honggfuzz

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    env:
      DEBIAN_FRONTEND: noninteractive

    name: Build Honggfuzz (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - arch: amd64
            os: ubuntu-24.04
          - arch: arm64
            os: ubuntu-24.04-arm
    container: ubuntu:20.04

    steps:
      - name: Install dependencies
        run: |
          apt update && apt install -y \
            binutils-dev \
            build-essential \
            clang \
            libblocksruntime-dev \
            libiberty-dev \
            liblzma-dev \
            libunwind8-dev \
            pkg-config \
            zlib1g-dev

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build Honggfuzz
        # Build a somewhat portable release of Honggfuzz inspired by
        # https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/precompile_honggfuzz
        run: |
          # Enable static linking of most system libraries
          export BUILD_OSSFUZZ_STATIC=true
          export CC=clang
          # Quoting https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/precompile_honggfuzz#L33
          #   These CFLAGs match honggfuzz's default, with the exception of -mtune to
          #   improve portability and `-D_HF_LINUX_NO_BFD` to remove assembly instructions
          #   from the filenames.
          export CFLAGS="-O3 -funroll-loops -D_HF_LINUX_NO_BFD"
          make

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp -r honggfuzz hfuzz_cc/ artifacts/
          rm artifacts/hfuzz_cc/*.c
          tar -czvf honggfuzz-${{ matrix.arch }}.tar.gz -C artifacts .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: honggfuzz-${{ matrix.arch }}
          path: honggfuzz-${{ matrix.arch }}.tar.gz

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download AMD64 artifact
        uses: actions/download-artifact@v4
        with:
          name: honggfuzz-amd64

      - name: Download ARM64 artifact
        uses: actions/download-artifact@v4
        with:
          name: honggfuzz-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            honggfuzz-*.tar.gz
          generate_release_notes: true
